context:
  version: "5.10.0"

package:
  name: tape
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/tape/-/tape-${{ version }}.tgz
  sha256: 632c606fd4257069b358466b16224a5e4f2930957fe94a4d5826ba97d27cb50f

build:
  number: 0
  noarch: generic

requirements:
  build:
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - tape --help

about:
  license: MIT
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: tap-producing test harness for node and browsers
  homepage: https://github.com/tape-testing/tape
  repository: https://github.com/tape-testing/tape

extra:
  recipe-maintainers:
    - danielnachun
