context:
  version: "5.10.1"

package:
  name: tape
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/tape/-/tape-${{ version }}.tgz
  sha256: 0f497bfafbe3e6d9626c52f448a28c59c8d376b46c2574741f9a03580b7b4b62

build:
  number: 0
  noarch: generic

requirements:
  build:
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - tape --help

about:
  license: MIT
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: tap-producing test harness for node and browsers
  homepage: https://github.com/tape-testing/tape
  repository: https://github.com/tape-testing/tape

extra:
  recipe-maintainers:
    - danielnachun
